# Generated by Django 4.0.4 on 2022-05-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
